site_name: Grancypher Wiki
site_description: Grancypher 使用说明

theme:
  name: material
  language: zh
  logo: img/Logo.png
  favicon: img/Logo.ico

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 深色模式

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 浅色模式

plugins:
  - search


nav:
  - Grancypher: index.md

  - 快速开始:
      - 安装: install.md
      - 第一次使用: getting-started.md
      - 代理设置: proxy.md

  - 功能:
      - 书签: features/bookmarks.md
      - 分屏与置顶: features/split-pin.md
      - 自适应画面: features/resize.md
      - 太郎与用户脚本: features/tarou-js.md
      - 快捷键与速达键: features/shortcuts.md
      - 多账号与设置: features/settings.md

  - 常见问题: faq.md
  - 更新日志: changelog.md

extra_css:
  - stylesheets/sky-journal.css
  - stylesheets/sky-journal-extension.css

markdown_extensions:
  - attr_list
  - md_in_html